artifact_location: file:///mnt/c/Users/saisa/AppliedMachineLearning/assignment_2/mlruns/431075443274287447
creation_time: 1741084637935
experiment_id: '431075443274287447'
last_update_time: 1741084637935
lifecycle_stage: active
name: SMS Spam Classification
